### ISSUE TITLE
Formatting is not left-aligned for group headings in Enketo Express

### ISSUE THREAD

**Issue by cagulas** [onaio/enketo-express#10]
New Enketo Express on zebra.ona.io has some formatting issues.  Group headings are now centered instead of left-aligned:

![screen shot 2015-09-11 at 11 36 04 am](https://cloud.githubusercontent.com/assets/3488986/9828878/5e8c0068-58c2-11e5-8435-57890993e6b6.png)

Replaces https://github.com/onaio/core/issues/566

**Comment by ivermac** [comment]
This works for me locally but doesn't when I deploy. I tried deploying without copying `node_modules` from the previous deploy as well as change the different enketo themes but none fix the bug.

**Comment by ivermac** [comment]
It seems both the `kobo` and `formhub` css theme files have the headers aligned in the centre as seen in the screenshots below:
**As it is**
![image](https://cloud.githubusercontent.com/assets/1128227/11839280/8f4efdc8-a3fd-11e5-8820-329c45d4d140.png)

**When centre alignment is removed**
![image](https://cloud.githubusercontent.com/assets/1128227/11839284/946051c2-a3fd-11e5-80ca-35691e09ff6f.png)
