### ISSUE TITLE
Redirect after Enketo Express edit form record loads page not found

### ISSUE THREAD

**Issue by cagulas** [onaio/enketo-express#12]
Using the new Enketo Express on zebra.ona.io, the edit form submission in Enketo Express works, but the redirect after you submit the edited record loads this error page:

![screen shot 2015-09-11 at 10 43 54 am](https://cloud.githubusercontent.com/assets/3488986/9828981/a9478b5c-58c4-11e5-8137-268a40af685c.png)

The edit is successful though, and one can see the edited record on Ona.

**Comment by geoffreymuchai** [comment]
This is a zebra issue related to the returnUrl that is called once a submission is editted

**Comment by pld** [comment]
Is this in zebra or core? Where in code do/can we set the `returnUrl` value?

**Comment by pld** [comment]
Also, according to @ivermac (and the docs, http://apidocs.enketo.org/#/post-instance) this should be `return_url`

**Comment by ivermac** [comment]
I made [pull request](https://github.com/kobotoolbox/enketo-express/pull/336) that fixes this problem which was merged and added to [this release](https://github.com/kobotoolbox/enketo-express/releases/tag/1.20.1)
