### ISSUE TITLE
Refresh banner appears even though form wasn't replaced recently

### ISSUE THREAD

**Issue by cagulas** [onaio/enketo-express#17]
The refresh banner in Enketo that alerts the user to refresh the page, because there's a new version of the form, appears when it shouldn't appear.

For example, on the WHO DCP site, the new IPC form was authored and uploaded to the site on Sept 24, 2015, and it was never replaced since then, so users shouldn't be getting this refresh banner when opening the form.  I don't get the banner when I use the login that I use regularly, but when I log in with an account I've never logged in to before (i.e. sldcp16), the refresh banner appears about a minute after I open the form.

**Comment by ivermac** [comment]
This should be fixed now. re-open if it still occurs
