### ISSUE TITLE
Question type of "file" results in Enketo upload error for word, excel files

### ISSUE THREAD

**Issue by pld** [onaio/enketo-express#22]
From @cagulas:

Enketo allows for the question type of "file" where you can upload documents with the form submission.  Does this only support pdf files?  I thought the scope for this was it was supposed to allow .doc .xls files as well.  Currently, I get the following upload error when I try to upload a word or excel file (pdf file submission worked).

"The data server for your form or the Enketo server is down. Please try again later or contact support@ona.io."

@ukanga can you clarify what the expected behavior is supposed to be?

**Comment by ukanga** [comment]
@carolyn it should support pretty much any format, server being down would be a separate issue not related to the type-file issue.

The question would be, why are we getting the server is down error.

**Comment by cagulas** [comment]
Just tested this again, and all file types seem to be working.  No longer getting a server error.
