### ISSUE TITLE
Enketo form appears to briefly distorted as it loads when a user clicks on edit #4198

### ISSUE THREAD

**Issue by skambo** [onaio/enketo-express#26]
**Environment**
MacOSX/Chrome/SIM

**To reproduce**
- log in as simconsortium user , go to a table, click on a row and select 'edit'
- Enketo form briefly shows up with no layout, see below
  ![dfid](https://cloud.githubusercontent.com/assets/4996911/15322483/dc88f6c8-1c45-11e6-8dd8-cc13b9e41848.gif)

<img width="1280" alt="screen shot 2016-05-17 at 3 23 10 pm" src="https://cloud.githubusercontent.com/assets/4996911/15322490/e27de750-1c45-11e6-9fd4-710464a46e50.png">

**Expected result**
-Form loads properly when 'edit' is selected

**Comment by ivermac** [comment]
I don't know if we can control this. The form loads well finally and you should also consider the sim server has enketo, zebra and core are running on the same machine

**Comment by pld** [comment]
closing, if this appears on non-SIM servers we can reopen
