### ISSUE TITLE
Preview form error message saying not found in formlist

### ISSUE THREAD

**Issue by cagulas** [onaio/enketo-express#27]
onasupport user has can view and download role on a project, so the user should be able to load the preview enketo form to view it, but instead, the error message saying form not found in form list is displayed.

link to enketo preview form: https://enketo.ona.io/preview/::Yzo6

error message screenshot:
![screen shot 2016-09-06 at 10 44 27 am](https://cloud.githubusercontent.com/assets/3488986/18266955/a999cf34-7425-11e6-9a70-d433001398b1.png)

**Comment by ivermac** [comment]
@faith-mutua and I have tested the enketo url above - https://enketo.ona.io/preview/::Yzo6 - on chrome (standard mode and incognito mode as well) and it works for us. I'm closing this. Re-open if the issue can be replicated.
