### ISSUE TITLE
Some photos not appearing in Enketo webform

### ISSUE THREAD

**Issue by cagulas** [onaio/enketo-express#28]
Iqbal from the OpenSRP team notified us that not all of his photos are appearing in his webform. 

Here is the [form](https://ona.io/emas/17772/138519) (shared with onasupport with can submit permissions).

Here is the direct link to the [webform](https://enketo.ona.io/x/#Yzo6).

Help scout ticket: https://secure.helpscout.net/conversation/247447260/4363/?folderId=488731

**Comment by ivermac** [comment]
I haven’t had time to look at this. Not sure what’s really happening. Could either @faith-mutua @bmalina @dkwamboka @msschroeder ask Martjin if he’s experiencing the same by creating an issue on enketo express parent repo

**Comment by faith-mutua** [comment]
@ivermac, sure let me ask Martijn

**Comment by faith-mutua** [comment]
Waiting for @MartijnR response on this issue https://github.com/kobotoolbox/enketo-express/issues/568

**Comment by faith-mutua** [comment]
@ivermac, @pld @ukanga this is what Martijn had to say concerning this issue `I think the issue lies on the Ona side, but I'd be happy to look at this issue to figure out where it occurs and fix it if it's an Enketo bug. I would have to bill Ona for this, so I'll wait for the go-ahead from your side.` 
Please advise on the way forward.

**Comment by pld** [comment]
Let's look into it first and see if it's on the Ona side

**Comment by faith-mutua** [comment]
@pld, @ukanga  when can this be scheduled to be looked into on the Ona side?

**Comment by ukanga** [comment]
This issue is very much a user issue, they are using images that have spaces when they probably should not. Instead of "Apple Oranges.jpg" they should use "Apple_Oranges.jpg" and upload the images that way.

**Comment by msschroeder** [comment]
@ukanga okay. So we can inform the user and now can close the issue. I believe.

**Comment by ukanga** [comment]
Yes

**Comment by msschroeder** [comment]
Client has been inform. Closing issue
