### ISSUE TITLE
Page fails to respond when keying in a repeat count value

### ISSUE THREAD

**Issue by dkwamboka** [onaio/enketo-express#37]
When entering a repeat count value on Enketo, the page fails to respond/ takes along time  if you key in the number, but works if you use the arrows in the Textbox to increase your integer value to the number you wish to input.

When testing on two forms, one with more calculations or fields (bigger repeat group) this occurs at numbers as small as 5.
**Enketo link:** [Longest Pregnancy Duration](url)
[Actual form](https://docs.google.com/spreadsheets/d/1u6tHvmGxP85IQpsQmSDxCbRoVmRdTsHU_M8KDmj3Ad4/edit#gid=1646011133)

When trying with a form with a smaller repeat group, this occurs at larger numbers e.g 10.
**Enketo link:** [Repeat Count](https://enketo.ona.io/x/#phvp)
[Actual form](https://docs.google.com/spreadsheets/d/1Zkk4qCLGE4NFBrXhHdxk6ktDKwV-OgxHhod4bJ4z4bU/edit#gid=912459735)

**Comment by faith-mutua** [comment]
Closing this for now. Issue seems to have been fixed by updating Enketo to latest version v1.65.1.
