### ISSUE TITLE
Webform error when pulling data form CSV or linked dataset

### ISSUE THREAD

**Issue by samwata** [onaio/enketo-express#39]
When pulling data from a CSV or another form using linked dataset and try to open Enketo it returns this error
![image](https://user-images.githubusercontent.com/23456184/42887911-b53faf28-8aaf-11e8-9036-ba9ee2b126cb.png)

When you unlink either CSV or linked dataset Enketo opens fine.

**Comment by faith-mutua** [comment]
@samwata this doesn't seem to be an issue now. Pulling data from a pre-loaded CSV file/linked dataset is working fine. Closing this for now. You can re-open if it's still an issue on your end.
