### ISSUE TITLE
Form reload in Enketo Express cuts off top of form

### ISSUE THREAD

**Issue by cagulas** [onaio/enketo-express#9]
In the new Enketo Express on zebra.ona.io, if you submit a form, the page reloads to a blank form.  In this case, it cuts off the top of the form where it says "Offline-enabled forms....":

![screen shot 2015-09-11 at 11 52 40 am](https://cloud.githubusercontent.com/assets/3488986/9828946/aba20306-58c3-11e5-92b6-9be5080c628c.png)

**Comment by ivermac** [comment]
closing this, reopen if it will be recreated
